#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width        0
bspc config window_gap          0
bspc config focused_border_color 
bspc config normal_border_color "#000000"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#4 keyboard layout
setxkbmap -option grp:alt_shift_toggle kz,us &

#cursor fix
xsetroot -cursor_name left_ptr

#polybar
$HOME/.config/polybar/launch.sh

#AutoStart applications
#alacritty &
kitty &
sxhkd &
picom --config $HOME/.config/picom/picom.conf & 
nitrogen --restore &
dunst &
polybar &
